1.
    a.
        i.
            D
        ii.
            D
        iii.
            A
    b.
        Because B and C have the same number of protons, and only different numbers of neutrons. This means they are isotopes of each other, and so must have the same chemical properties.
    c.
        1.6726 * 10^(-24) * 3 + 1.6740 * 10^(-24) * 4
        = 1.17138 * 10^(-23) ~= 1.1714 * 10^(-23)
2.
    a.
        i.
            Metals are malleable because they have ordered and regular layers of positive cations which can slide freely over each other without much resistance.
        ii.
            Metals are good conductors of electricity because they have a sea of delocalised electrons which are free to move to carry charge and conduct electricity.
    b.
        Extraction using carbon is most suitable as electrolysis is expensive. Electrolysis is used when the metal is more reactive than carbon as you cannot extract using carbon in that case, but Iron is less reactive than carbon, so extraction using carbon can be used, which is cheaper.
    c.
        The student could add sodium hydroxide to a sample of each solution. The Iron (II) sulfate will produce green precipitate whereas the Iron (III) sulfate will produce brown precipitate.
3.
    a? [Make a flashcard from the image of the apparatus to identify it as fractional distilation]
        D
    b? [What is the condenser called?]
        X: Thermometer
        Y: Condenser
        Z: Beaker
    c?
        The teacher could attempt to boil the ethanol. It should boil at exactly 78 degrees celcius; if it does, it is pure.
4.
    a.
        i?
            Fizzing and Bubbling
            Increase in temperature (visible steaming etc)
        ii? [Is base solid or liquid? Difference between base and alkali]
            The final color of the universal indicator will be blue or purple as LiOH will be produced whe Lithium is added to water, which is alkaline, and so the solution becomes a base. Universal indicator turns blue or purple in the presence of a base.
    b? [Is moles = mass/RFM's mass in grams?]
        550/24000 moles of H2
        2 * 550/24000 moles of Li
        2 * 550/24000 * 7 = 0.32083... ~= 0.321g of Lithium.
    c.
        i? [Different reactions of alkali metals with water]
            There is flame
        ii.
            Because the atomic radius of potassium is larger than lithium, the valence electron in potassium is further away from the nucleus so experiences less attractive force so is more easily lost; and hence potassium is more reactive.
5.
    a.
        i.
            Pipette
        ii.
            Yellow to orange
        iii.
            Because universal indicator's color change is not sudden enough so the results will not be precise enough.
    b.
        i.
            23.80
            2.15
            21.65
        ii.
            (21.65 + 21.3 + 21.5)/3 = 21.48333 ~= 21.48 cm^3
    c.
        The student should perform the titration once again; i.e.
            1. Add sodium hydroxide solution into the beaker using a pipette of 25 cm^3 capacity, taking care to take the reading at eye-level at the bottom of the meniscus;
            2. Add dilute nitric acid of the same concentration into the burette;
            3. Add exactly 21.48 cm^3 of dilute nitric acid into the beaker using the burette;
            4. Allow the resultant solution to evaporate and crystalise on a watch-glass or similar until there is no/little liquid left
            5. During this process, crystals will form.
            6. Pat dry using a paper towel, and then leave on some paper towel and allow it to further air-dry if necessary
        Noting that no indicator is added in the titration as it is not necessary and would result in impure crystals of sodium nitrate.
6.
    a.
        The crude oil is separated into fractions by fractional distilation by:
            1. Heating the crude oil until it vaporizes
            2. Passing the vapor into a fractionating column
            3. The fractionating column has a gradient of temperature; i.e. it is cooler at the top and warmer at the bottom
            4. Different fractions of crude oil condense at different places in the fractionating column (at their boiling points)
            5. These can be extracted from those points.
    b.
        i.
            600-700 degrees celcius; presence of an alumina catalyst
        ii.
            This is because they have a lower boiling point and are more flammable, so are more useful as fuels in e.g. cars.
        iii.
            612 + 4 * 414 + 193 - (4 * 414 + 348 + 2 * 276)
            = -95 ~= -100 kJ/mol
        iv?
            This is because there are stronger bonds between the atoms in the product than between the atoms in the reactants. This results in a negative molar enthalpy change, which means the reaction is exothermic.
7.
    a.
        i.
            Propanol
        ii.

        iii.
            2 * 12 + 2 * 16 + 3 * 1 + 1 + n(12 + 2) = 242
            => n = 13
        iv?
            water
    b.
        i.
            mols of sodium hydroxide solution: 0.15 * (25/1000) = 0.00375
            divided by 2 is the number of moles of dicarboxylic acid C: 0.001875
            0.001875/(17.5/1000) = 0.1071428... ~= 0.107 mol/dm^3
        ii.
            

            