1.
    a.
        Freezing
        Condensing
        Sublimation
    b.
        i.

        ii.
            A
    c? [Is liquid water (l) or (aq)?]
        l, s
2.
    a.
        i.
            Oxygen
        ii.
            Nitrogen
        iii.
            Chlorine
    b.
        Because it is made up of more than one element (hydrogen and chloride) bonded together (in this case covalently), and has a net charge of 0.
    c.
        D
3.
    a.
        i.
            1.
                Water
            2.
                Oxygen
        ii? [Is rust Iron (III) oxide?]
            Hydrated Iron Oxide
    b.
        i.
            Method A prevents iron from rusting by preventing it from being exposed to both oxygen and water. Method A is a barrier method; the paint physically prevents oxygen or water (in the form of e.g. water vapour) from coming into contact with the iron. Since the iron does not contact both of the substances needed for it to rust, it cannot rust.
        ii.
            Galvanisation
        iii.
            Method B prevents iron from rusting even when the zinc coating is scratched because Iron is less reactive than the zinc, so the zinc corrodes instead of the iron. Electrons flow from the zinc to the iron, preventing the formation of iron ions to bond with the oxygen or the water in the air.
4.
    a.
        The student should draw a line in pencil on the chromatography paper near the bottom but not at the bottom so that there is ample room below the line. The student should then put dots of each ink as spaced out from each other as possible on that line. The student should then fill a beaker with solvent, ensuring that the level of solvent does not exceed the amount of space below the line. The student should then put the chromatography paper into the beaker line-end-first, ensuring that the solvent does not directly touch the line or any of the ink-dots. The student should then wait for thirty minutes, or until the dyes have visibly separated, at which point the dyes can be identified as they will have separated from each other.
    b.
        i.
            E must contain a dye which is insoluble in the solvent, since the dot did not move from the start line at all. This must mean that the dot did not dissolve in the solvent, as otherwise it would move to some degree from the start-line.
        ii.
            Inks A and C contain the same dye, because one of its constituent inks (one of the dots vertically above A and C) moved the same distance in A as in C. This implies it is the same dye, since usually only the same dye have the same RF value, which is distance travelled by the dot divided by distance traveled by the solvent front. Since the dots traveled the same distance, it implies they have the same RF value, which implies they are teh same dye. 
        iii.
            The student can use a ruler to measure the distance from the start line of the solvent front and the distance from the start line of the dye in ink C. The student can then divide the distance from the start line of the dye by the distance from the start line of the solvent front, obtaining a value which is less than one.
5.
    a.
        A glowing splint will relight.
    b.
        A catalyst increases the rate of a reaction by lowering the activation energy required for the reaction by providing an alternative pathway for the reaction to occur. This increases the rate of reaction as now collisions of particles are more likely to have sufficient energy for the reaction to occur.
    c.
        i.
            A.
                Conical flask
            B.
                Gas syringe
        ii.
            Draw dotted lines on the graph;38 cm^3
        iii.
            x=6, x=10; (65-50)/4 = 3.75 cm^3/min
6.
    a.
        i.
            AlCl3
            ZnSO4
            (NH4)3N
        ii.
            Aluminum Sulfate
    b.
        When magnesium and chlorine ions form magnesium chloride, a magnesium atom loses two electrons from its outer shell to form a magnesium ion, and two chlorine atoms each gain an electron in their valence shells to form two chloride ions. These ions are then joined together by strong electrostatic forces of attraction.
    c.
        i.

        ii.
            There are strong electrostatic forces of attraction between the shared pairs of electrons and the nuclei in a covalent bond.
7.
    a.
        i.
            The student surrounds tube B with ice to lower the temperature in tube B and to prevent it from heating up beyond 100 degrees celsius, the boiling point of water, to allow the water to condense in tube B with less water vapour diffusing away.
        ii.
            The student will know when all of the water of crystallisation has been given off when the mass of tube B stops increasing.
    b? [What color is copper sulfate when anhydrous?]
        Anhydrous copper sulfate turns blue from white.
    c?
        moles of magnesium sulfate = 6/120 = 0.05. Moles of water = 22.1/18 = 1.22777777. So x must be 1.227777777/0.05 = 24.555555 ~= 24.6
8.
    a.
        Because this reaction produces gaseous carbon dioxide, which escapes through the cotton wool, so mass is lost to the atmosphere.
    b.
        Because at the start the concentration of hydrochloric acid is the highest, so there are the most collisions between the HCl in the solution and the marble chips, and this higher rate of collisions leads to a higher rate of reaction. As the reaction goes on, the HCl in the solution is used up, so the concentration drops and there are fewer and fewer collisions between the marble chips and the HCl. This lower rate of collision leads to a lower rate of reaction.
    c.
        This is because the marble chips were in excess; the HCl was used up.
    d.
        i.
            The concentration of the hydrochloric acid
            The size and hence surface area of the marble chips
        ii.
            When the temperature is increased, the average kinetic energy of the HCl particles increases, as kinetic energy is proportional to kelvin temperature. Since the mass of the particles is constant, this implies they move faster. So, there are more frequent collisions (as they are moving faster) between the hydrochloric acid particles and the marble, and these collisions have more energy as the kinetic energy of the particles increased, so the collisions are more likely to surpass the activation energy and lead to a reaction. The increased rate of collisions and increased energy when colliding leads to an increase in the rate of reaction.
9.
    a.
        This is because aluminum is a good conductor and glass is a poor conductor of heat, so with aluminum more heat is transferred to the water instead of lost to the environment.
    b.
        i.
            Soot/carbon
        ii.
            This is because incomplete combustion of the fuel occurs in the spirit burner.
    c.
        i.
            4.2 * 100 * 50 = 21000 ~= 20000
        ii.
            1.84/46 = 0.04 moles of ethanol
            20 kJ, so
            20/0.04 = 500 kJ/mol
            exothermic, so -500 kJ/mol
    d.
        i.
            5
        ii.
            RFM of butanol = 12 * 4 + 10 + 16 = 74
            so 3.7/74 = 0.05 moles of butanol
            so (2 + 2 + 5) * 0.05 = 0.45 moles of gas in total
            0.45
10.
    a.
        i.
            Ethane is an alkane, and is saturated, so will not react with bromine as it requires UV light to react with bromine as it is an alkane and is saturated.
        ii.
            C2H5Br + HBr
            condition: presence of UV light/sunlight
        iii?
            Orange -> colorless
    b.
        i.
            Same functional group
            Similar chemical properties
        ii.
            Because they have the same molecular formula (C4H8) but different displayed formulae.
        iii.

    c?
        The reactant is a monomer, ethene. Ethene will be liquid at room temperature. Ethene's longest chain of carbons is 2, and the carbons are bonded by double bonds, so ethene is unsaturated. In contrast, polyethene can have carbon chains of infinite length, is solid at room temperature, and all bonds in polyethene are single bonds so it is saturated.
11.
    a.
        i.
            2PbS + 2O2 -> 2PbO + S2O2
        ii.
            Sulfur dioxide should not be released into the atmosphere as it can cause acid rain, which is bad for the environment.
        iii.
            moles of lead oxide = 892 * 10^6 / 233 = 4000000 moles.
            There are half as many moles of CO2, so 2000000. So, 2000000 * 44 = 88000000 = 88 tonnes.
        iv?
            Lead (II) sulfide is a solid with a very high melting point at room temperature because the ions in lead sulfide have strong electrostatic forces of attraction with each other in a lattice structure, which requires a lot of energy to overcome, so have a high melting point. The ions are held fixed in place by those strong electrostatic forces of attraction. 

            Sulfur dioxide has weak intermolecular forces of attraction between molecules of sulfur dioxide. When heated, these weak forces are overcome, allowing the sulfur dioxide molecules to move past each other freely, and hence be gaseous.
    b.
        90.7/207 : 9.3/16
        = 90.7/207/(9.3/16) : 1
        ~= 0.75 : 1
        = 3 : 4
        so Pb3O4
    