1.
    a.
        Because deep sea fishing involves going very far from land, where the fisher may become susceptible to storms, large waves, faulty equipment, etc while being far enough away that it is difficult for help to arrive
    b.
        1.
            Because storms or other natural disasters could kill off or otherwise destroy offshore fish farms, which would need time to recover. This would change how much fish can be produced.
        2.
            Because it is not possible to say for certain the amount of new fish sired by each mother, and the rate of survival of those fishes, which will change how much fish can be produced
        3.
            Because unpredictable economic pressures may cause differing levels of investment into smart fish farming at sea, which will change how much fish can be produced.
    c.
        Fish farms cause pollution as they concentrate large amounts of fish in a single area, which secrete waste, which can pollute the environment; also, because fish farms use large amounts of growth stimulants, antibiotics, and pesticides to increase yield, which may diffuse out of the fish farm, polluting the environment. The aforementioned may cause issues such as eutrophication or antibiotic resistance in bacteria.
    d.
        i.
            The fish farmer could apply large amounts of antibiotics and pesticides into the water in their fish-farm to kill bacteria and disease-spreading pests in the fish farm to reduce the incidence of disease in a fish farm.
        ii.
            Large amounts of antibiotics could cause bacterial resistance to antibiotics and large amounts of pesticides may unintentionally kill other organisms, disrupting the food chain in the local ecosystem.
    e.
        Since the water movement is often faster in the deep sea, any chemicals used in fish farming will be dispersed more quickly over a larger area, so will be less concentrated, which may reduce any inadvertent effect on the local ecosystem.
    f.
        Because they are farther away from land, so any inspection would be more costly and hence likely less frequent; and because the faster waters, deeper sea, and remote location may mean that measuring key markers such as the health and population of local species may be more difficult, and hence less feasible, to monitor. Regulation requires monitoring to be effective.
    g.
        Because they can be fed byproducts of food-crops, which ordinarily could not be sold, so they can be bought for a very low price, so it is less expensive for the fish farmer to feed the fish, lowering operating cost and increasing profit.
    h.
        Because smaller fish farms represent multiple points of failure, and so one accident does not cause as much environmental damage; also, because farmed fish do not need to be transported as far, and transportation releases (amongst other things) carbon dioxide, which is a greenhouse gas which causes global warming as it traps and reflects heat.
2.
    a.
        D
    b.
        i.
            .9/(2.5) = .36 = 36%
        ii.
            .5 * (110/70) = 0.78571428571 ~= 0.786L
        iii.
            Vomit contains water, which is additional water lost. In addition, vomiting may prevent water which is drunken from being absorbed by the body, as it may be immediately vomited out. This may cause body water content to lower.
            Diarrhoea is faeces which contains much more water than normal. This means more water is lost from the body, so blood concentration may as a result increase.
            High Temperature may induce sweating, which is a loss of water in itself. This means body water content may lower.
    c.
        Body mass is higher in summer than in winter. Water intake in one day is higher in winter than in summer. Urine concentration is higher in summer than in winter.

        Body mass may be higher in the summer because less energy is required in the summer and because food is likely more abundant in the summer. Less energy is required because, as rodents and mammals, degus must be homeotherms, so in the winter must use more energy to maintain their body temperature; in addition, in the winter, plants are likely dead or less available, so it will probably consume less food. Consuming more food and less energy usage means there may be more excess energy to be stored as fat; in contrast, if in the winter the combination of more required energy and less food to consume means the degu consumes less energy as food than it requires, it will burn stored fat to release energy, causing a reduction in bodily mass. However, the change in bodily mass between winter and summer is not very drastic, so this may not be a very severe effect.

        Water intake is likely higher in the winter because there is more water for the degu to intake. This is because more rain falls, so more water can be taken up by plants and so when the degu eats the plants it gets more water. This is in contrast to the summer, where almost no rainfall occurs, so plants slowly dry out, so for roughly the same consumption of plants the degu gets less water.

        The degu getting less water in the summer also likely leads to the higher urine concentration in the summer than in the winter. This is because urine becomes more concentrated as water is reabsorbed out of the collecting duct, and more water is reabsorbed when blood concentration is high, and that is high when there is less water in the body. A combination of more water usage due to the summer heat and the much lower intake of water means that more water will need to be reabsorbed via osmosis out of the collecting duct, so the urine concentration must be higher.
3.
    a.
        i.
            D
        ii.
            B
        iii.
            When a person enters a cold environment, temperature sensors in the skin detect the change in temperatures and send a signal to the hypothalamus. The hypothalamus in turn sends signals via motor neurons to effectors, causing vasoconstriction, hair to stand up (in animals which have hair on their skin), cessation of sweating, and shivering. Vasoconstriction is when sphincter muscles surrounding arterioles in the skin constrict, causing blood to flow through deeper vessels, reducing heat loss. Hair stands up to trap air as insulation, again reducing heat loss. Sweating is a method to shed excess heat; here, that is not necessary, so that stops, reducing heat loss. Shivering is the rapid contraction and relaxation of muscles, which generates heat energy.
    b.
        For both young and old, an increase in heat strain is correlated with an increase in mean skin temperature in degree and with an increase in mean sweating rate per cm^2 of skin. However, given the same heat strain, it holds that both skin temperature and mean sweating rate per cm^2 of young people is higher than that of old people.

        The reason for the increase in skin temperature when heat strain increases seems obvious: an increase in external temperature means there is a lower temperature gradient between the skin/sweat and the ambient air, so methods of cooling such as sweating etc which rely on that temperature gradient become less effective, so core and skin temperature both increase. As body temperature increases, an increase in rate of sweating is only natural, as the body increases the rate of sweating in order to try to cool the body off more.

        Likely, the lower skin temperature in older people reflects a lower core body temperature, which would also explain the lower mean sweating rate. This is likely because as we age our metabolism slows down, so less heat is produced by our bodies, so even under an increase in external temperature, the older people's body temperature is relatively lower than the young people's, so hence their mean sweating rate, which is governed by body temperature, is not as high; and their mean skin temperature also is not as high.
4.
    a.
        i.
            Concentration of carbon dioxide
        ii.
            To prevent the organisms from dropping into the hydrogen-carbonate indicator solution while still allowing gas to flow freely
        iii.
            volume of indicator
    b.
        the empty tube had no change in color as expected.

        for tube A, the indicator is red, indicating low levels of carbon dioxide. This is likely because leaves were contained in the container and there was light, so photosynthesis occurred, and hence carbon dioxide was converted into oxygen, so there was less carbon dioxide, so the indicator turned red.

        For tube B, there was no light. The indicator is yellow, indicating higher levels of carbon dioxide than initial. This suggests that the leaf respired its stored starch (which does not require light) and in that respiration produced carbon dioxide.

        For tubes C and D, the indicator is yellow in both. This indicates higher levels of carbon dioxide than initially. One is light and one is dark, but that does not matter, as maggots respire their food-stores in both light and dark, and respiration produces carbon dioxide.
    c.
        The indicator remains orange because, in the light, the leaves converts carbon dioxide to oxygen via photosynthesis, reducing the amount of carbon dioxide in the tube, except that the maggots convert oxygen to carbon dioxide via respiration, so in fact there is little or no change in amount of carbon dioxide in the test tube, so the color of the indicator does not change.
5.
    a.
        i.
            76/(17/100) - 76 - 62.8 - 49.3 = 258.958823529 ~= 259 Mha
        ii.
            62.8/(12 * 20) = 0.261666666667 ~= 0.262 Mha per month
        iii.
            Because the total amount of tree cover lost in the world is less than the total amount of tree cover in russia. More concretely, letting x be the amount of tree cover in russia before the loss between 2001 to 2021 occured, 76 = .1 * x so x = 760. Letting y be the amount of tree cover lost from 2001 to 2021 in the entire world, 76 = .17 * y so y = 447.058823529 Mha lost. With these numbers, those percentages can exist.
    b?
        Deforestation leads to desertification, loss of habitat for leaf-dwelling organisms, loss of habitat for forest-dwelling organisms; loss of food for herbivores, etc, which ultimately reduces biodiversity and may lead to the extinction of species.
6.
    a.
        A Gene is a sequence of three bases that codes for a sequence of amino acids to fold into a protein. The Genome is the entire genetic code of an organism.
    b.
        - DNA helix opens up; hydrogen bonds between the base-pairs break
        - MRNA enters the helix
        - adjacent complementary base pair
        - Polymerase binds the free nucleotides back into a polymer
        - MRNA leaves the DNA through the nuclear pore and brings the genetic information to the ribosomes in the cytoplasm
        - DNA helix zips up again
    c.
        Because this is not a frameshift mutation, so any changes are local;
        Because there might be no change to the resultant protein/because the changes to the resultant protein might be so small that the active site is similar enough to function the same;
        Because the swap might be in non-coding DNA which would likely not affect the sequence of amino acids and hence lead to the same protein and enzyme, so the function does not change
    d.
        eye color,
        height+