1.
    a.
        1.
            urea
        2?
            water
    b.
        1.
            Patient does not need to go to the hospital for dialysis regularly, which may be costly
        2?
            A kidney transplant is permanent; the patient does not need to maintain access to a hospital.
    c?
        When the immune system detects a foreign body, lymphocytes produce antibodies, which bind to the foreign body. The foreign body is then swallowed by phagocytes using pseudopodia, and taken into the phagocytes' vacuole, where enzymes are secreted to break it down.

        There is also fever to try to kill the disease, inflammation to protect the afflicted area(s), coughing and sneezing to try to expel the pathogen.
    d?
        The chances of rejection are lower if the kidney comes from a close relative because the kidney would be more genetically similar to the receiver. This would mean that the body is less likely to identify it as a foreign body and attack it, so the chances of rejection are lower.
    e.
        i.
            ld2020 1040; ld2021 429; dd2020 2283; dd2021 1836
            (1040 - 429)/1040 - (2283 - 1836)/2283 = 0.391704... ~= 39.17%
        ii?
            Because living donors may not want to give up one of their kidneys as if their remaining kidney fails they will in turn need a donation. Moreover, some donors may not be fit for the surgery while alive.
    f?
        A suitable kidney likely means a kidney which the patient is not likely to reject and which is healthy. E.g. a kidney coming from a donor of the same blood type
    g?
        Because kidney disease is more common in people of those ethnic origins, so there is a higher demand of kidneys than for people of white ethnic origin; but, there are not many donors from those communities, so there is a lower supply, so kidney donors are particularly required. Also, it is not likely, due to differences in genetic makeup, that people of these ethnic origins would be able to receive kidneys from people of white origin.
2.
    a? [Density of water]
        Since we know the difference in temperature (final - initial temperature), and we know water's specific heat capacity (4.2 joules per gram-degree celcius), and we know the mass of the water since we know the density of water and we can multiply the volume of water (20 cm^3) by the density of water, and the water absorbs the (heat) energy released by 1g of the grain, we can calculate the increase in energy in the water using the formula energy = 4.2 * mass of water * (end temperature - starting temperature); and the formula mass of water = density of water (in g/cm^3) * volume of water (20 cm^3).
    b.
        The scientists can repeat the experiment with fresh water and grain three times per grain-type.
    c.
        i.
            A twisted waste gas pipe increases the amount of time the hot gas leaving the grain can transfer energy to the water as the gas must travel for longer while transferring energy. If there is significant energy left in the hot gas as it leaves the apparatus, then that is energy which is not measured, reducing accuracy. Hence, this increases accuracy.
        ii.
            So complete combustion occurs as there is more oxygen as opposed to incomplete combustion which happens when there is not enough oxygen, which releases less energy.
    d.
        i.
            7 * .65 = 4.55g
        ii.
            Rice has the most carbohydrate, but the least protein. Oats have a high amount (but not the highest) of fat, protein, and carbohydrate. Rye has the least fat, but also a low amount of protein. However, they have a relatively high amount of carbohydrate compared to wheat.

            Wheat has the highest amount of protein, but also the highest amount of fat, and the lowest amount of carbohydrate.

            Energy-wise, oats > rice > wheat > rye. Fibre-wise, rye = wheat > oats > rice.

            A long-distance athlete likely needs an energy-dense food, but, being an athlete, would also need high protein. The athlete would likely not want to consume foods with a high amount of fat. If that is not an issue, however, wheat would be a good choice, as it has the highest amount of protein. If it is an issue, oats is likely the best choice, as it is the most energy dense and also has a respectable amount of protein.

            However, the long-distance athlete might already get enough protein from another source. In that case, rye would be a good choice, as it has a high amount of fibre and a low amount of fat.

            Right before race-day, the athlete might choose to consume rice as rice has the most carbohydrates, to provide energy in delayed-release form.
3.
    a?
        Stem cells are different from most body cells because they are not specialised, and can differentiate into (in the case of embryonic stem cells) any other specialised cell, or (in the case of adult stem cells) into red blood cells via erythropoiesis.
    b? [How does the fibrin/fibrinogen come in?]
        When there is damage in a blood-vessel in the body, a blood clot is formed to prevent severe blood loss, which would be fatal. Platelets are vital in the formation of blood clots as they trap red blood cells to form the blood clot.
    c?
        Vaccination is the introduction of weakened viruses or bacteria, or fragments thereof, causing antibodies to be produced. These antibodies, being soluble proteins, stay in the plasma until the body is infected for real, at which point they are able to react quicker than if vaccination had not occurred, which helps prevent the disease from reproducing or reproducing as quickly, hence protecting the body from disease.
    d?
        Blood stem cells can be used to treat a variety of blood disorders because a transplanted blood stem cell will then reproduce to make more blood stem cells, and also differentiate into well-formed red and white blood cells.
4.
    a.
        i.
            A.
        ii.
            D.
        iii.
            If a person moves to a hot environment, vasodilation occurs. Sphincters surrounding the blood vessels in the skin relax, allowing blood to flow closer to the surface of the skin so heat can be transferred.
    b.
        i.
            Sweating rate in litres per hour.
        ii.
            draw dotted lines;
            1.7 litres/hour * 15/60 = 0.425 litres
        iii.
            As running speed increases, the sweating rate increases. This is likely because there is waste heat generated as muscles contract to make the person run, increasing body temperature, so sweating occurs to cool the person down. As the person runs faster, more heat is generated, so more sweating occurs.

            There is more sweating at all speeds in the hot and humid environment. This is likely because the environment being hot means the person's body temperature was already high, and being humid means sweat is less effective at cooling the person down. Moreover, the rate of increase in volume of sweat is lower for the cool and dry environment at first, indicating that the increased gradient in temperature had increased cooling somewhat and hence that not as much of an increase in sweat was necessary.
5.
    nucleus
    egg
    nucleus
    divide
    embryo
    uterus
    surrogate

6.
    a.
        i.
            Because there may be other limiting factors e.g. temperature once the crop has absorbed all required minerals
        ii? [definition of eutrophication, general]
            Applying more water than needed may lead to flooding or the soil becoming loose or saturated, potentially killing any insects or animal which burrow in the soil.

            Applying too much nitrogen fertilizer may lead to eutrophication. Combined with the excess water, which will carry the nitrogen fertilizer to nearby water bodies such as rivers, this may lead to excess growth of e.g. algae which will consume much of the oxygen in the water, starving other aquatic life. This may harm the food-chain as this may mean that some fishes' population will decrease..
        
    b.
        Carbon monoxide binds irreversibly to haemoglobin in red blood cells, and prevents oxygen from binding to said haemoglobin. Too much exposure can lead to not enough oxygen being supplied to body cells for respiration and eventual suffocation.
    c.
        C
    