1.
    a.
        Cardiomyopathy can cause heart failure because the walls of the heart have become stretched, thickened, or stiff. This inhibits the regular rhythm of contraction of the heart which is required to pump blood around, or may cause the walls of the heart to become damaged in that process.
    b?
        The atria are the chambers of the heart which receive blood from the veins and pump that blood into the ventricles. The left atrium receives blood from the pulmonary vein, and the right atrium receives blood from the vena cava and pumps blood into the right ventricle.
    c.
        Blood in the pulmonary artery is deoxygenated and does not have a lot of oxygen; blood in the aorta is rich in oxygen as it has passed through the lungs.
    d.
        A heart-lung bypass machine keeps the patient alive by acting as a pump and as a lung by keeping blood circulating in the patient, as well as oxygenating the blood as it pumps it and removes oxygen, replacing the functionality of the heart and the lungs. The patient cannot live if he does not have oxygenated blood moving through his arteries, so this is why it is used.
    e.
        The patient needs to be given immunosuppressants as the new heart will not have the exact same antigens, so otherwise will be treated as a pathogen and attacked by the patient's immune response. Immunosuppressants suppress the immune system, reducing immune response and reducing the amount of damage to the new heart so it can function properly.
    f?
        Patients should not smoke after their heart transplants because smoking irritates the heart and causes build-up of cholesterol, which may cause the transplant to fail or may cause the cholesterol to build up and another heart attack to happen
    g.
        A diet with appropriate (not too much but not too little) proportions of micro- and macro-nutrients such as carbohydrates, protein, fiber, vitamins etc
    h.
        200 * 75% = 150 people
    i.
        Because strenuous activities would require more oxygen and would require the heart to beat faster and with more force, which might stress the heart and cause the transplant to fail
    j.
        Because they will have to take immunosuppressants, which indiscriminately suppresses the immune system, so the immune system will be less able to fend off and prevent from multiplying small amounts of bacteria in food, and so the patient will be more susceptible to food poisoning.
2.
    a.
        i.
            C
        ii.
            B
    b.
        The pollen tube grows through the style and allows the nucleus of the pollen to move out of the stigma and to enter the ovum and fuse with the ova and fertilize it.
    c.
        i.
            (600-330)/3 = 270/3 = 80
        ii?
            Since Actinomycin D prevents transcription and cycloheximide prevents translation, both of which are required in synthesis of proteins, the rate of pollen growth in both solutions are lower than in control. This is because protein synthesis is required for growth, and since transcription and translation are prevented, growth of the tube cannot happen.
    d?
        The scientist could observe pollen grains by taking a sample of the liquid, placing it between two glass slides, and using an optical microscope.
3.
    a.
        A
    b.
        i.
            All glucose is reabsorbed via selective reabsorption to be reused for energy in the body in the proximal convoluted tubule, so the mass of glucose goes to zero.
        ii.
            1-1500/180000 = 0.991666666667 = 99.2%
        iii.
            C
    c.
        This decreases urine production as ADH causes the kidney tubules (specifically the collecting duct) to become more permeable. Hence, more water is reabsorbed, so the volume of urine decreases. The urine also becomes more concentrated.
4.
    a.
        i.
            With the nucleus removed
        ii?
            The single cell divides by mitosis several times to develop into an embryo
    b.
        Although there were more successful pregnancies using adult body cells, the there were less offspring produced, suggesting a high rate of miscarriage. In addition, those offspring were short-lived, suggesting that adult body cells do not produce healthy foetuses/babies. In addition, more surrogates were used for adult body cells (twice as many), so relatively there were less offspring produced (2/2 = 1 vs 2/1 = 2) for adult body cells, though there are still relatively more successful pregnancies. This, though, still leads to the conclusion that there is a high rate of miscarriages. Hence, fetus body cells is more successful in cloning monkeys, because they produce healthier babies with less chance of miscarriage and the babies are not short-lived.
5.
    Using a bomb calorimeter, place 1g of crushed potato chips of the first type in the chamber. Measure the temperature of the water, and then (supplying oxygen etc) ignite the potato chip. Measure continuously the temperature of the water, and take the peak temperature, and subtract from that the starting temperature. Repeat this three times and take the average of those repetitions. Then, repeat all of this with the second type of chip. Whichever chip has the lowest average temperature increase contains the least energy.
6.
    a.
        Create a coordinate-system for each field. Then, use a random number generator to generate a coordinate. Use quadrats: place a quadrat at that coordinate and count the number of each plant in that quadrat.
    b.
        i.
            (7+3+2+1+2)/5 = 15/5 = 3
        ii.
            quadrat is 0.25m^2, so 3 * 4 = 12 dandelions per m^2
    c.
        There are more numbers of all species in field A than in field B. Furthermore, in field B, there are some species which are simply not present. However, the maximum number of plants per quadrat is the same in both fields (7), which is much higher than the rest in field B, suggesting clumps of dandelions. It seems overall that violets, heathers, and buttercups are do not fare well in these fields when compared to dandelions, as dandelions in both fields are much more numerous.
    d?
        The students could attempt to plant buttercups in a waterlogged environment as well as dandelions. If only the dandelions thrive, then this is possibly a factor. The students could also attempt to waterlog a portion of field A where there are buttercups, or attempt to plant buttercups in a waterlogged portion of field A. If the buttercupts do not thrive, then this is possibly a factor. The students could also install water drainage in field B. If buttercups appear (planting may be necessary to accelerate the process), then this is possibly a factor. Finally, the students should measure the water content in the soil of field B. If it is relatively dry (in relation to field A), and is not excessively wet, then this is likely not the reason.
7.
    a.
        Cell differentiation is important as the body contains many specialised cells, and for them to develop from a single fertilized egg cell, it must be able to differentiate into those specialised cells, which are vital for life (red blood cells for carrying oxygen e.g.)
    b.
        i.
            D
        ii.
            Adult stem cells cannot become all cell types, so may not be suitable for certain diseases. In addition, adult stem cells may be rejected by the patient. In contrast, embryonic stem cells are cloned from the patient so will not be rejected, and can become all cell types, but there are ethical concerns about cloning and creating an embryo just for medical treatment.