1.
    a.
        Add iodine solution to a small piece of bread. If the iodine solution turns dark purple, it has starch.
    b.
        i.
            B
        ii.
            A
2.
    a.
        i.
            6 * 10^4
        ii.
            D
    b.
        i.
            A person with anaemia is often tired because they don't have enough red blood cells. Red blood cells deliver oxygen to cells for aerobic respiration, which produces energy. Without enough red blood cells, the person's cells will not have enough oxygen so will not have enough energy as they cannot respire aerobically, and anaerobic respiration produces less energy, so the person has less energy, which means they are often tired.
        ii.
            A person with leukopena is more likely to get infections because they don't have enough white blood cells. White blood cells prevent infections by producing antibodies and engulfing pathogens, so not enough white blood cells would mean that they are more likely to get infections as it would take longer to fight off bacteria.
3.
    a.
        Small Intestine
        Oesophagus
    b.
        These microorganisms may be useful to the cow because they can break down plant cell walls, which are tough, allowing the cow's enzymes to access the nutrients (e.g. starch stored in the vacuole) stored within the plant cell. It is difficult and would likely be expensive for the cow to produce its own enzymes which digest the cell wall. So, those microorganisms form a symbiotic relationship with the cow.

    c.
        Since injecting GH into cows means you can obtain the same volume of milk from fewer cows, this may mean that farmers will have less cows. So, there will be less digestion-induced methane. Methane is a greenhouse gas, so it causes climate change, so if the aforementioned happens, climate change would indeed reduce.

        However, it may be that farmers will keep the same amount of cows and simply get more milk -- the aforementioned description of events assumes that supply of milk will exceed or is already exceeding demand so much so that price of milk would substantially drop and cause keeping the same amount of cows globally to be untenable. However, this is not given. In addition, GH may be expensive to produce or to safely inject; this would cause smaller farmers to be outcompeted, possibly increasing greenhouse gas emissions as food will have to be transported further from larger industrial farms. Also, we are not told whether GH production causes climate change. 

        In addition, GH may cause an increase in digestion, as GH stimulates growth, and you need energy to grow, and cows get their energy from digestion. If the decrease in amount of cows cannot offset any increase in digestion, climate change will not reduce.
4.
    a.
        A D
    b.
        i.
            6/30 = 1/5 = 0.2 g per hour
        ii.
            The dry mass of yeast can be found by first measuring the mass of the flask and the 200cm^3 of glucose solution, and then (after adding yeast) measuring the flask, glucose, and yeast, and subtracting the former from the latter.
        iii.
            The dry mass of yeast
        iv.
            1.
                Temperature of the glucose solution, as if the solution is too hot the yeast will die and hence not increase in mass
            2.
                The availability of oxygen (concentration of oxygen in air), as if there is not enough oxygen the yeast will have to anaerobically respire which will produce less energy and lead to less increase in dry mass
5.
    a.
        Bacteriophages can introduce modified DNA into bacteria so as to genetically modify them.
    b.
        i.
            magnesium
        ii.
            Taking two identical fields which are next to each other, plant crops such as wheat in them. Plant the same crop in both fields. In the first field, use method A, and in the second, use method B. After six months, or after the appropriate amount of time to harvest the selected crop, harvest both fields, and measure by weight the yield. Since the fields are next to each other, sun exposure, rain exposure, temperature etc will be the same. Repeat this experiment for three harvests if necessary.
6.
    a.
        To control what enters and leaves the cell
    b.
        2^2 * 3.14 * (1 - 45%)
        = 6.908mm^2
        ~= 6.91 mm^2 available
    c.
        ii.
            C
        iii.
            (115 + 34 + 9 + 5) / (13 + 150 + 442 + 299 + 115 + 34 + 9 + 5)
            = 0.152764761012
            ~= 15.3%
    d.
        There is indeed a lower percentage of people having heart attacks in the statin group. This may indicate that statins reduce the risk of heart attacks.

        However, only one type of statin was tested. It may be that only that type of statin reduces the risk of heart attacks.

        In addition, we do not know how many people are in each group of people. It may be that there are not enough people to make sure that that difference in percentage of heart attacks is not just random noise.

        Moreover, the scientist only tracks the people for four years. If statins increase the risk of heart attacks massively after four years, this experiment will not discover that, and the conclusion will be false.
7.
    a.
        i.
            A section of DNA on a chromosome that codes for a specific sequence of amino acids to form a protein
        ii.
            grey hair
    b.
        Grey white = Gg

        G   g
      G GG  Gg
      g Gg  gg

      parent genotypes = Gg, Gg
      offspring genotypes = GG, Gg, gg
      offspring phenotypes = 25% white hair, 75% grey hair; 1 : 3

    c.
        The scientist could cross the mouse with a mouse with white hair. The mouse with white hair must be homozygous recessive, since white hair is recessive. If the mouse with grey hair is heterozygous, then one of the offspring will have white hair. If it is homozygous, none of the offspring will have white hair. Of course, a sufficient number of offspring must result from the cross to eliminate the effects of random chance.
    d?
        Most phenotypic features are controlled using multiple genes. For instance, height is controlled by more than one gene. In addition, oftentimes, non-coding genes around the gene also control phenotypic features.
8.
    a.
        Asexual reproduction:
            - produces genetically identical clones
            - does not require a mate/other organism
        Sexual reproduction:
            - introduces genetic variation
            - requires another organism
            - Allows for natural selection and for organisms to adapt to their environments
                - survival advantage
    b.
        i?
            A
        ii?
            C
        iii.
            Structure B produces oestrogen and progesterone. Oestrogen stimulates the development of secondary sexual characteristics in women, as well as suppressing the release of FSH, and stimulating the release of LH, and causing the uterine lining to thicken. Progesterone also helps maintain the uterine lining, and both serve to regulate the menstrual cycle.
    c.
        i.
            3.22 * 62.1 = 199.962 ~= 200 million
        ii?
            The mean number of sperm released is a better measure of fertility than semen volume or sperm concentration because semen volume has little bearing on fertility -- it is the sperm that fertilises; so long as there is enough semen to deliver the sperm it has no other bearing. Mean sperm released is better than mean sperm concentration because this means there is more sperm which means it is more likely some will survive and reach the egg; increase in concentration (but decrease in actual number released) will not do this.
        iii.
            (202 - 142)/202 = 0.29702970297 ~= 29.7%
9.
    a.
        i.
            Bladderwrack, microscopic algae
        ii.
            Lobster, crab
        iii.
            bladderwrack -> flat winkle -> crab -> herring gull
    b.
        i?                        [Common Seal]
                               [Lobster]
                     [Limpet                           ]
            [                 Microscopic Algae                  ]
        ii.
            The amount of energy available to the organisms decreases by roughly a factor of ten per level in the chain along this food chain because energy is lost in e.g. movement, growth of cells or organs which cannot later be digested by another organism, dead organisms not eaten, etc.
10.
    a.
        i.
            The student could remove all the starch from the leaf by soaking it in a solution with amylase at 37 degrees celcius for a long time, until a sample of the leaf in iodine solution no longer causes dark purple to appear
        ii.
            So that when we test for produced starch later we are not getting a false positive from already-produced starch
    b? How is chlorophyll removed?
        wear safety goggles
    c.
        Control the temperature of the leaf and keep it the same with and without light.
    d?
        Leaves have a layer of palisade cells called the palisade layer which have lots of chloroplasts which contain chlorophyll for photosynthesis. This layer is close to the top surface of the leaf so will receive light for photosynthesis. In addition, the spongy mesophyll has lots of pores to allow for good air-flow through the leaf, so carbon dioxide can be taken in and used in photosynthesis. Also, there are xylem to transport water into the leaf for use in photosynthesis.
11.
    a.
        i.
            Structure C is the cornea, which focuses the light most of the way. Structure A is the lens, which can change its shape to change how much light rays are bent. This allows it to become more convex to focus on light from a near object, or become less convex to focus on light from far away. Structure D is the ciliary muscles, which contract to reduce tension in the suspensory ligaments and to make the lens become more convex to focus on light from a near object. The lens has to be more convex to focus on a near object because those light rays will be diverging.

        ii.
            Structure B is the iris. The Iris Reflex occurs when the bright light is detected by the retina -> a nervous signal is sent to the brain -> a nervous signal is sent back to the eye/circular muscles -> Structure B constricts when there is bright light, lowering the amount of light that enters the eye, so the retina is exposed to less light, so is dimmer, so is not damaged.
        
    b.
        i.
            To break down any pathogens which may have gotten into the eye to prevent infection of the eyeball, as white blood cells cannot easily access the surface of the eye
        ii.
            So the eye is not irritated as pH7 is neutral, so other structures of the eye are not broken down/irritated by a basic/acidic liquid.
    