1.
    a.
        D
    b.
        D
    c.
        C
    d.
        The orbit of the moon is much less eccentric than the orbit of a comet. In addition, the moon orbits the Earth, whereas a comet orbits the Sun. The comet also goes much further away from the sun than the moon goes from the Earth.
2.
    P S Q R
3.
    a.
        i.
            12.5 - 0 = 12.5 cm
        ii.
            12.5/100 * 2.35 * 1000 * 1000 * 1000 = 293750000 ~= 3 * 10^8 m/s
    b?
        Could damage skin cells or cause 
4.
    a.
        B
    b?
        Transfers energy; is longitudinal
    c.
        i.
            Draw the perpendicular line to the tangent at the point where the incident ray intersects the mirror
        ii.
            Reflected ray at same angle from normal; arrow on reflected ray facing opposite direction
    d.
        i.
            120/1.5 = 80 A
        ii.
            Because there is a current in the wire and electricity is flowing, there is a magnetic field surrounding the wire.
5.
    a?
        The wooden ring makes the apparatus safer for the student to use as wood is an insulator, so if the student needs to adjust the apparatus he will not get burned. In addition, the wooden ring also acts to counterbalance the tacks so that the apparatus will not fall over or otherwise unexpectedly and autonomously disassemble, which has the potential of scattering hot metal and burning the student.
    b.
        The end of the metal strips over the flame becomes hot as it is heated. This means that the mean kinetic energy of the metal atoms in that area increases. These atoms collide with neighbouring atoms, transferring this energy to them. The metal strips heat up beginning from the end at the flame, which is the hottest; the heat travells towards the end furthest from the flame, which is the coldest. As the end furthest from the flame heats up, those metal atoms bump into the wax molecules, transferring their energy into the wax, and ultimately melting it.
    c.
        i.
            A bar chart is used as the dependent variable is numeric and continuous, but the independent variable is categorical (and hence discontinuous).
        ii?
            The student could improve the reliability of their results by repeating the experiment three times, or by using a pressure-sensor to automatically stop the timer when a tack falls.
        iii.
            I do not agree with the student's conclusion. This is because it takes energy to melt wax, so the material that transmits energy the best will melt the wax the quickest. Iron, however, melted the wax the slowest, as evidenced by the fact that it took the pin longest to drop on iron.
6.
    a.
        i.
            3/2.5 = 1.2ms^-2
        ii.
            Area under the curve/line
        iii.
            2.5 * 3 / 2 = 7.5/2 = 3.75 m
    b.
        15/5^2 = 0.6 == 60/10^2 = 0.6 so the results support this suggestion
7.
    a.
        i? What are alpha/beta/gamma particles notated as? 
            Hydrogen ion
        ii?
            When it decays, the number of protons stays the same; the number of neutrons increases by one.
    b.
        - Y axis labelled: percentage of carbon-14 remaining
        - X axis labelled: Age of samples (years)
        Y axis scale: 0-100, step 10
        X axis: 0-10000 step 1000
        CURVE of best fit
        iii.
            8374.26074
    c.
        i.
            Because they absorb carbon-14, so a radioactive substance (carbon 14) has been placed inside them, the definition of contamination
        ii.
            Since more carbon-14 is in the tree, there would be higher radioactivity, falsely indicating that the wood was younger than expected. However, it is likely that a sample of wood produced ~1950 could not have been accurately carbon-dated anyways
8.
    a.
        from star towards centre of galaxy
    b.
        i.
            3 * 10^8 * 3.2 * 10^7 = 9.6*10^15 ~= 10^16
        ii.
            (29000 * 10^16/1000) / 220 = 1.3181818182*10^15 ~= 1.32 * 10^15
9
    a.
        i.
            Uranium-235
        ii.
            Nuclear fission is a chain reaction whereby a slow moving neutron hits a nucleus, causing it to split into two smaller nuclei and release two more neutrons, which go on to hit other nuclei and continuing the chain reaction. During that splitting, energy is released.
    b.
        i.
            The turbine is spinned by the steam passing through it. This moves the coils of wire through the magnets' magnetic field, causing magnetic flux in the wire. This induces a current in the coils of wire, which flows into the wires for transmission of electricity.
        ii.
            By lowering the control rods to slow down the chain reaction of fission, or else turning the turbine blades so the turbine is pushed less by the steam
        iii.
            AC rapidly oscillates whereas DC flows continuously in one direction
10.
    a.
        i.
            Voltage = current * resistance
        ii.
            5.8/13000 = 0.000446153A ~= 0.000446A = 4.46mA

    b.
        i.
            A parallel to 200 ohm resistor but in series with 13 kohm resistor
        ii?
            13 kohm: decrease as current is now split between the two paths of resistors, and the 200 ohm resistor will draw the majority of the current

            battery: increase as net resistance decreases when resistors are added in parallel, and the added resistor is much lower in resistance, and current = voltage/resistance so when resistance decreases current increases
11.
    a.
        i.
            pressure difference = height * density * g
        ii.
            (117 - 12) * 1000 / (1.36 * 10^4) / 9.8 = 0.787815126m ~= 0.788m
    b.
        i.
            The pressure of trapped gas increases as its temperature increases because as the temperature increases, the mean kinetic energy of the particles of the gas increase. These particles are moving randomly, so will collide with the walls of the barometer; when they collide, they exert a force. When the mean kinetic energy of the particles of gas increases, so does this force; since pressure is force/area (area = area of walls the barometer), the pressure increases as area is constant.
        ii.
            12/23*38 = 19.8260869565 ~= 19.8 kPa
12.
    a.
        Chemical energy -> kinetic energy (food to fingers moving);
        Kinetic energy -> potential energy (fingers moving the marble -> lifts the marble)
        kinetic energy -> sound energy (placing the marble at point A)
        potential energy -> kinetic energy (marble rolls down the pipes marble run)
        kinetic energy -> sound energy (marble drops down the vertical chutes/marble rolls down the marble run)
    b.
        i.
            The student could mark out a short distance in a flat straight line from point B. The student could then, using a stopwatch, start the time when the marble crosses point B, and then stop the time when the marble crosses that marker. The student could then measure the distance, and calculate the speed by using the formula speed = distance/time, since both time and distance are known.
        ii.
            exit KE = 1/2 * 5.5/1000 * 0.76^2 = 0.0015884 J
            Starting GPE = 0.21 * 5.5/1000 * 9.8 = 0.011319J
            so energy lost = 0.011319 - 0.0015884 = 0.0097306 ~= 0.00973 J
        
        
        