1.
    a.
        i.
            argon
        ii.
            nitrogen
        iii.
            hydrogen
    b.
        Global warming
    c.
        Bubble through limewater, turns cloudy from clear
2.
    a.
        i.
            Measuring cylinder
            Volumetric Pipette
        ii.
            Because it is more precise, and so the added volume will be closer to exactly 25 cm^3, and that precision is required in a titration as titration is sensitive to changes in volume
    b.
        i.
            Yellow
        ii.
            Because it continually changes color and does not have a clear end-point
    c.
        (((21.5/1000)*.6)/2)/(25/1000) = 0.258
    d.
        It would not be a suitable acid to use in this titration as barium sulfate is insoluble, so the precipitate produced could interfere with the reading of the result.
3.
    a.
        C
    b.
        A
    c.
        Fluorine is more reactive than Chlorine, because chlorine has a larger atomic radius, so the force with which it attracts electrons from other atoms/molecules to form a chloride ion is lower than the force which fluorine can exert to form fluoride, as the positively charged nucleus of fluorine can be closer to the other molecule's electrons, and the electrostatically attractive force is not shielded by the other electrons. Fluorine and Chlorine have similar chemical properties, however, since they both have seven electrons in their valence shell.
    d.
        i.
            Li + Cl -> LiCl
        ii.
            Test for chloride:
                - add nitric acid
                - add silver nitrate
                - white precipitate, which dissolves in dilute ammonia solution
            Test for Lithium:
                - flame Test
                - use platinum wire
                - dip in hydrochloric acid to clean and then put in flame
                - dip in acid again
                - pick up sample of formed substance with wire
                - put in flame
                - if it is lithium, the flame turns reading
            
            if both tests return positive results, then the product is likely Lithium Chloride.
4.
    a.
        Bright white flame
        White residue
    b.
        Magnesium loses two electrons to become an ion [2,8]^{2+}; oxygen gains two electrons to become the ion with configuration [2,8]^{2-}
    c.
        i.
            Because magnesium is more reactive than carbon
        ii.
            Magnesium conducts electricity because it is bonded metallically, there is a sea of delocalized electrons which are free to move to carry charge and hence conduct electricity.

            Magnesium Chloride conducts electricity when molten because, when molten, the magnesium chloride ions are no-longer held in place by the forces of the giant ionic lattice and so the ions are free to move to carry charge and hence conduct electricity (in contrast, were it to be solid, the ions would be held in place in a giant ionic lattice and magnesium chloride would not conduct electricity as there would be neither electrons nor ions that are free to move to carry charge)
    d.
        i.
            Because magnesium ions gain electrons to become magnesium, and reduction is gain of electrons
        ii.
            Cl^{-} -> Cl + e^{-}
5.
    a.
        i.
            40/12 : 6.7 : 53.3/16 
            10 : 20.1 : 9.99375
            ~= 10 : 20 : 10
            = 1 : 2 : 1
            so CH_{2}O is the empirical formula of the compound.
        ii.
            CH3COOH

            H OH
        H   C-C=O
            H
    b.
        i.
            Na(COOH)2 + CO2 + H2O
        ii.
            Bubbling as CO2 leaves solution
    c.
        i?
        ii.
            That the reaction is a reversible reaction
        iii.
            Concentration of reactants and products remain the same
    d.
        i.
            condensation polymerisation
        ii.
            O=CHCH2CH2-CH=O; HOCH2CH2OH
6.
    a.
        ((20 * (10^6))/80) * 2 * 24 = 12000000 dm^3
    b.
        because air contains oxygen, which would likely react with the molten magnesium to form magnesium oxide, and so introduce a source of contaimination and impurities. In contrast, argon is much less reactive than air or oxygen, and so will not react/react less with the reactants, so there will be less impurities.
    c.
        - Alloy disrupts the ordered structure of a metal
        - different sized atoms are inserted into the lattice structure
        - layers cannot slide over each other as easily
        - so require more force to deform
        - so stronger
7.
    a.
        Soot
    b.
        18.2/(0.92/46) = 910 ~= 900; -900 because it's exothermic
    c.
        1. Because incomplete combustion must have occurred, as evidenced by the presence of soot, which would release less energy;
        2. Because heat may have escaped to the atmosphere as there was no lid via evaporation, or as not all heat is transferred to the calorimeter
    d.
        i.
            let x = CH bond
            4x + 2 * 498 - 890 = 2 * 805 + 4 * 463
            4x = 2 * 805 + 4 * 463 - 2 * 498 + 890
            x = (2 * 805 + 4 * 463 - 2 * 498 + 890)/4
            x = 839
        ii.
                  _
                |   \
            ___|     |
                     |
                      |
                       \
                        -------
                        