1.
    a.
        i.
            Silicon
        ii.
            Magnesium
        iii.
            Mercury
        iv.
            2.8.5.
    b.
        Neon is unreactive as it has a full outer shell of electrons, so does not easily lose/gain electrons and hence does not easily ionically or covalently bond or bond in any method with other elements.
2.
    a.
        B
    b.
        i.
            B
        ii.
            C
        iii.
            CuCO3 + O2 -> CuO + CO2
    c.
        ((100 - 27))/(100 + 280) = 0.192105263158 = 19.2105263158% ~= 19%
    d.
        An increasing amount of carbon dioxide in the atmosphere is likely to cause a problem for the environment as carbon dioxide is a greenhouse gas, which traps and reflects heat, causing global warming to worsen; this can lead to other issues such as rising sea levels and flooding of low-lying habitats.
3.
    a?
        C6H12O6 -> 2C2H6O + 2CO2
    b.
        i.
            Phosphoric acid
            30 degrees celcius
            60-70
        ii.
            advantage: lower temperature and pressure mean its safer and cheaper equipment is necessary
            disadvantage: less pure so not suitable for medical use and has to be refined via e.g. fractional distillation.
    c.
        Because fermentation needs to be an anaerobic process, so air is removed to allow for this; in addition, air would oxidize ethanol into ethanoic acid, which is undesirable.
    d.
        i.
            [REMEMBER TO DIVIDE THROUGH BY RFM IN DOING EMPIRICAL FORMULA CALCULATIONS]
            60/12 : 13.3/1 : 26.7/16
            5 : 13.3 : 1.66875
            5/1.66875 : 13.3/1.66875 : 1
            2.99625468165 : 7.97003745318 : 1
            ~= 3 : 8 : 1
            so C3H8O
        ii.
                H   H   H
                |   |   |
            H---C---C---C---O---H
                |   |   |
                H   H   H
4.
    a.
        Volumetric pipette
    b.
        yellow, red
    c.
        To give it better contrast to better and more clearly see the color change of the indicator at the end-point
    d.
        To mix the indicator, acid, and alkali so that the pH is even in the solution and so make the experiment more accurate as there will not be portions of the solution which are neutralized and portions which are not.
    e.
        Several results within 0.2 cm^3 of each other.
    f.
        (15/1000) * 0.18 = concentration * (25/1000) * 2
        concentration = (15/25/2) * 0.18 = 0.054 mol/dm^3
    g?
        The OH ion is a proton acceptor in this reaction as it reacts with (accepts) a H+ ion, which is a hydrogen atom with one less electron, and since hydrogen only has one electron this means H+ is a proton, so it accepts a proton in this reaction.
5.
    a.
        Add to the sample NaOH. Observe that a blue precipitate forms. This indicates that there are Copper (II) ions. If it does not form, then the test shows that there are no such ions.
    b?
        Copper metal forms as there are free Cu^{2+} ions in the solution. When power is turned on, the negative electrode becomes negatively charged as electrons move from the positive to the negative electrode as a result of the power becoming turned on. There is an electrostatic attraction between the copper ions in the solution and the negatively charged negative electrode. So, the copper ions move to the negative electrode and collect to form copper metal.
    c.
        A orange-pink metal.
    d.
        i.
            Glowing split relights in the presence of oxygen.
        ii?
            2H2O -> 4H^{+} + O2 + 4e^{-}
        iii.
            Because electrons are lost (on the right of the half-equation), and oxidation is loss of electrons.
6.
    a.
        i?
            Sulfuric acid
        ii.
            A fruity smell is detected.
        iii.
            Methyl ethanoate
    b.
        i.
            C-O and O-H.
        ii.
            Because a O-H bond is made and a C-O bond is made in the product, and a C-O bond and a O-H bond is broken. Enthalpy change = bonds broken - bonds made, but the bonds broken are the same as the bonds made, so the enthalpy change must be zero.
7.
    a.
        Because it binds irreversibly and preferentially to haemoglobin, causing not enough oxygen to be carried to our cells, causing asphyxiation.
    b.
        There is no effect when a nickel catalyst is used as a catalyst simply increases the speed at which equilibrium is reached, but has no effect on the position of the equilibrium itself; consequently, no more or less hydrogen is produced.
    c.
        i.
            Temperature is lowered. There is no change in pressure. The position of equilibrium moves to resist this change in temperature. Since the rightwards reaction is endothermic, and the leftwards exothermic, the position of equilibrium must move left; hence, less hydrogen is produced, so the yield is lower.
        ii.
            Temperature is not changed. But, pressure is lowered. There are more moles of substances on the right of the reaction (3 + 1 = 4) than on the left ( 1 + 1 = 2; 4 > 2). So, the position of equilibrium moves to counteract the decrease in temperature: i.e. it moves right. So, more hydrogen is produced, so the yield is higher.
    d.
        ((6.6 * (10^6)/1)/3) * 24 = 52800000 = 5.28 * 10^(7) dm^3
    